<template>
  <div class="clients-page">
    <header class="page-header"><div><p class="eyebrow">Base de clientes</p><h1>Clientes</h1><p class="subtitle">Encontre rapidamente contatos e histórico de atendimento.</p></div><button class="primary-action" type="button" @click="showForm = true">+ Novo cliente</button></header>
    <section class="toolbar" aria-label="Busca de clientes"><label class="search-field"><span>Buscar cliente</span><input v-model.trim="query" type="search" placeholder="Nome, telefone ou cidade" /></label><span class="result-count">{{ filteredClients.length }} clientes</span></section>
    <section class="client-list" aria-label="Lista de clientes"><article v-for="client in filteredClients" :key="client.id" class="client-card"><div class="avatar" aria-hidden="true">{{ initials(client.name) }}</div><div class="client-info"><h2>{{ client.name }}</h2><p>{{ client.phone }} · {{ client.city }}</p><small>{{ client.equipment }} equipamento(s) · Última visita: {{ client.lastVisit }}</small></div><a class="whatsapp-action" :href="whatsappLink(client.phone)" target="_blank" rel="noopener noreferrer">WhatsApp</a></article><p v-if="!filteredClients.length" class="empty-state">Nenhum cliente encontrado. Tente outro termo.</p></section>
    <div v-if="showForm" class="modal-backdrop" @click.self="showForm = false"><section class="modal" role="dialog" aria-modal="true" aria-labelledby="client-title"><button class="modal-close" type="button" aria-label="Fechar" @click="showForm = false">×</button><p class="eyebrow">Cadastro</p><h2 id="client-title">Novo cliente</h2><form @submit.prevent="saveClient"><label>Nome<input v-model.trim="newClient.name" required /></label><label>Telefone<input v-model.trim="newClient.phone" required type="tel" /></label><label>Cidade<input v-model.trim="newClient.city" required /></label><label>E-mail<input v-model.trim="newClient.email" type="email" /></label><label>Endereço<input v-model.trim="newClient.address" placeholder="Rua, número e bairro" /></label><div class="modal-actions"><button class="secondary-action" type="button" @click="showForm = false">Cancelar</button><button class="primary-action" type="submit">Salvar cliente</button></div></form></section></div>
  </div>
</template>
<script>
export default { name: "ClientsView", data() { return { query: "", showForm: false, clients: [{ id: 1, name: "João Silva", phone: "(11) 99999-1111", city: "São Paulo", equipment: 2, lastVisit: "12/08/2026" }, { id: 2, name: "Maria Souza", phone: "(11) 98888-2222", city: "Osasco", equipment: 1, lastVisit: "04/09/2026" }, { id: 3, name: "Carlos Oliveira", phone: "(11) 97777-3333", city: "Barueri", equipment: 3, lastVisit: "18/07/2026" }], newClient: { name: "", phone: "", city: "", email: "", address: "" } }; }, computed: { filteredClients() { const term = this.query.toLowerCase(); return this.clients.filter((client) => `${client.name} ${client.phone} ${client.city}`.toLowerCase().includes(term)); } }, methods: { initials(name) { return name.split(" ").map((part) => part[0]).slice(0, 2).join(""); }, whatsappLink(phone) { return `https://wa.me/55${phone.replace(/\D/g, "")}`; }, saveClient() { this.clients.push({ id: Date.now(), ...this.newClient, equipment: 0, lastVisit: "Ainda não atendido" }); this.newClient = { name: "", phone: "", city: "" }; this.showForm = false; } } };
</script>
<style scoped>
.clients-page { max-width: 980px; margin: 0 auto; padding: 150px 24px 80px; color: #15304a; }.page-header { display:flex; align-items:flex-end; justify-content:space-between; gap:24px; margin-bottom:30px; }h1,h2,p { margin-top:0; }.eyebrow { margin-bottom:6px; color:#0785a8; font-size:.75rem; font-weight:800; letter-spacing:.12em; text-transform:uppercase; }.subtitle { color:#668097; }.primary-action,.whatsapp-action { border:0; border-radius:10px; background:#067da2; color:#fff; cursor:pointer; font-weight:800; padding:13px 18px; text-decoration:none; }.toolbar { display:flex; align-items:end; justify-content:space-between; gap:20px; margin-bottom:16px; }.search-field { display:grid; gap:7px; width:min(100%, 480px); color:#15304a; font-size:.8rem; font-weight:800; }.search-field input { padding:13px; border:1px solid #cbdde3; border-radius:10px; font:inherit; }.result-count { color:#668097; font-size:.85rem; }.client-list { display:grid; gap:10px; }.client-card { display:flex; align-items:center; gap:16px; padding:18px; border:1px solid #dbe8ed; border-radius:15px; background:#fff; box-shadow:0 8px 24px rgba(21,48,74,.05); }.avatar { display:grid; place-items:center; width:46px; height:46px; border-radius:50%; background:#e4f4f7; color:#067da2; font-weight:900; }.client-info { flex:1; }.client-info h2 { margin-bottom:3px; font-size:1rem; }.client-info p,.client-info small { margin:0; color:#668097; }.client-info small { font-size:.8rem; }.empty-state { padding:30px; text-align:center; color:#668097; }.whatsapp-action { padding:9px 12px; font-size:.78rem; }.modal-backdrop { position:fixed; inset:0; z-index:10; display:grid; place-items:center; padding:20px; background:rgba(11,35,52,.48); }.modal { position:relative; width:min(100%,460px); padding:28px; border-radius:18px; background:#fff; }.modal form { display:grid; gap:15px; }.modal label { display:grid; gap:7px; font-size:.82rem; font-weight:800; }.modal input { padding:12px; border:1px solid #cbdde3; border-radius:9px; font:inherit; }.modal-close { position:absolute; top:14px; right:18px; border:0; background:transparent; font-size:1.6rem; cursor:pointer; }.modal-actions { display:flex; justify-content:flex-end; gap:10px; margin-top:8px; }.secondary-action { padding:12px 16px; border:1px solid #cbdde3; border-radius:9px; background:#fff; cursor:pointer; font-weight:800; }@media(max-width:600px){.clients-page{padding:130px 16px 50px}.page-header,.toolbar{align-items:stretch; flex-direction:column}.primary-action{width:100%}.client-card{align-items:flex-start; flex-wrap:wrap}.whatsapp-action{margin-left:62px}.search-field{width:100%}}
</style>

