<template>
  <div class="equipment-page">
    <header class="page-header">
      <div><p class="eyebrow">Operação técnica</p><h1>Equipamentos</h1><p class="subtitle">Organize os aparelhos por cliente e acompanhe a próxima manutenção.</p></div>
      <button class="primary-action" type="button" @click="showForm = true">+ Novo equipamento</button>
    </header>
    <section class="toolbar" aria-label="Busca de equipamentos">
      <label class="search-field"><span>Buscar equipamento</span><input v-model.trim="query" type="search" placeholder="Cliente, marca ou ambiente" /></label>
      <span class="result-count">{{ filteredEquipment.length }} equipamentos</span>
    </section>
    <section class="equipment-list" aria-label="Lista de equipamentos">
      <article v-for="item in filteredEquipment" :key="item.id" class="equipment-card">
        <div class="equipment-icon" aria-hidden="true">AC</div>
        <div class="equipment-info"><p class="eyebrow">{{ item.brand }} · {{ item.btu }} BTUs</p><h2>{{ item.type }} {{ item.model }}</h2><p>{{ item.client }} · {{ item.environment }}</p><small>Próxima manutenção: <strong>{{ item.nextVisit }}</strong></small></div>
        <span class="status" :class="item.status">{{ item.status === 'attention' ? 'Revisar' : 'Em dia' }}</span>
      </article>
      <p v-if="!filteredEquipment.length" class="empty-state">Nenhum equipamento encontrado.</p>
    </section>
    <div v-if="showForm" class="modal-backdrop" @click.self="showForm = false"><section class="modal" role="dialog" aria-modal="true" aria-labelledby="equipment-title"><button class="modal-close" type="button" aria-label="Fechar" @click="showForm = false">×</button><p class="eyebrow">Cadastro técnico</p><h2 id="equipment-title">Novo equipamento</h2><form @submit.prevent="saveEquipment"><label>Cliente<input v-model.trim="newEquipment.client" required /></label><label>Marca e modelo<input v-model.trim="newEquipment.model" required placeholder="Ex.: Split LG Dual Inverter" /></label><label>Ambiente<input v-model.trim="newEquipment.environment" required placeholder="Ex.: Sala" /></label><label>Capacidade<input v-model.trim="newEquipment.btu" required placeholder="Ex.: 12.000" /></label><div class="modal-actions"><button class="secondary-action" type="button" @click="showForm = false">Cancelar</button><button class="primary-action" type="submit">Salvar equipamento</button></div></form></section></div>
  </div>
</template>
<script>
export default { name: "EquipmentView", data() { return { query: "", showForm: false, equipment: [{ id: 1, client: "João Silva", brand: "LG", model: "Split Dual Inverter", type: "Split", btu: "9.000", environment: "Quarto", nextVisit: "12/02/2027", status: "ok" }, { id: 2, client: "Maria Souza", brand: "Samsung", model: "WindFree", type: "Split", btu: "12.000", environment: "Sala", nextVisit: "04/03/2027", status: "ok" }, { id: 3, client: "Carlos Oliveira", brand: "Daikin", model: "EcoSwing", type: "Split", btu: "18.000", environment: "Escritório", nextVisit: "18/10/2026", status: "attention" }], newEquipment: { client: "", model: "", environment: "", btu: "" } }; }, computed: { filteredEquipment() { const term = this.query.toLowerCase(); return this.equipment.filter((item) => `${item.client} ${item.brand} ${item.model} ${item.environment}`.toLowerCase().includes(term)); } }, methods: { saveEquipment() { this.equipment.push({ id: Date.now(), ...this.newEquipment, brand: this.newEquipment.model.split(' ')[0], type: 'Split', nextVisit: 'A definir', status: 'ok' }); this.newEquipment = { client: "", model: "", environment: "", btu: "" }; this.showForm = false; } } };
</script>
<style scoped>
.equipment-page { max-width:980px; margin:0 auto; padding:150px 24px 80px; color:#15304a; }.page-header { display:flex; align-items:flex-end; justify-content:space-between; gap:24px; margin-bottom:30px; }h1,h2,p { margin-top:0; }.eyebrow { margin-bottom:6px; color:#0785a8; font-size:.75rem; font-weight:800; letter-spacing:.12em; text-transform:uppercase; }.subtitle { color:#668097; }.primary-action,.status { border:0; border-radius:10px; background:#067da2; color:#fff; cursor:pointer; font-weight:800; padding:13px 18px; }.toolbar { display:flex; align-items:end; justify-content:space-between; gap:20px; margin-bottom:16px; }.search-field { display:grid; gap:7px; width:min(100%,480px); color:#15304a; font-size:.8rem; font-weight:800; }.search-field input,.modal input { padding:13px; border:1px solid #cbdde3; border-radius:10px; font:inherit; }.result-count { color:#668097; font-size:.85rem; }.equipment-list { display:grid; gap:10px; }.equipment-card { display:flex; align-items:center; gap:16px; padding:18px; border:1px solid #dbe8ed; border-radius:15px; background:#fff; box-shadow:0 8px 24px rgba(21,48,74,.05); }.equipment-icon { display:grid; place-items:center; width:46px; height:46px; border-radius:12px; background:#e4f4f7; color:#067da2; font-size:.8rem; font-weight:900; }.equipment-info { flex:1; }.equipment-info h2 { margin-bottom:4px; font-size:1rem; }.equipment-info p,.equipment-info small { margin:0; color:#668097; }.status { padding:8px 10px; background:#e3f6ee; color:#16734d; font-size:.75rem; }.status.attention { background:#fff1d9; color:#9a5b00; }.empty-state { padding:30px; text-align:center; color:#668097; }.modal-backdrop { position:fixed; inset:0; z-index:10; display:grid; place-items:center; padding:20px; background:rgba(11,35,52,.48); }.modal { position:relative; width:min(100%,460px); padding:28px; border-radius:18px; background:#fff; }.modal form { display:grid; gap:15px; }.modal label { display:grid; gap:7px; font-size:.82rem; font-weight:800; }.modal-actions { display:flex; justify-content:flex-end; gap:10px; margin-top:8px; }.secondary-action { padding:13px 18px; border:1px solid #cbdde3; border-radius:10px; background:#fff; color:#15304a; font-weight:800; }.modal-close { position:absolute; top:12px; right:14px; border:0; background:transparent; color:#668097; font-size:1.6rem; cursor:pointer; }@media(max-width:700px){.equipment-page{padding:125px 16px 50px}.page-header,.toolbar{align-items:stretch; flex-direction:column}.equipment-card{align-items:flex-start}.status{margin-left:auto}.equipment-info small{display:block; margin-top:5px}.modal-actions{flex-direction:column-reverse}.modal-actions button{width:100%}}
</style>
